export { default as Home } from './Home'
export { default as PlayDetail } from './PlayDetail'
export { default as SonglistDetail } from './SonglistDetail'
export { default as Comment } from './Comment'
// export { default as Setting } from './Setting'
// export { default as LoginScreen } from './LoginScreen/LoginScreen'
// export { default as SingleAppScreen } from './SingleAppScreen/SingleAppScreen'
// export { default as Tab1Screen } from './Tab1Screen/Tab1Screen'
// export { default as Tab2Screen } from './Tab2Screen/Tab2Screen'
